POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video JavaScript",
    "description": "This is video Two",
    "duration": 90

}

###

GET http://localhost:3333/videos


###

PUT  http://localhost:3333/videos/
Content-Type: application/json

###

DELETE http://localhost:3333/videos/