POST https://preventjs.onrender.com/videos
Content-Type: application/json

{
    "title": "Video Test",
    "description": "This is video Four",
    "duration": 90

}

###

GET https://preventjs.onrender.com/videos


###

PUT  https://preventjs.onrender.com/videos/
Content-Type: application/json

###

DELETE https://preventjs.onrender.com/videos/6276a563-922d-4af4-8fd9-4368b1e3aaa8